apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: uber
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'flask-backend'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['flask-backend:5000']
