apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: uber
type: Opaque
stringData:
  DB_CONNECT: 'mysql+mysqlconnector://root:AVdLiMJVPJoxcytCdJfiTyVbnFmxGcTT@gondola.proxy.rlwy.net:27694/railway'
  JWT_SECRET_KEY: 'your_secret_key'