apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: uber
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
