apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: m3t4-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: log
              mountPath: /app/logs
          env:
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /tmp
            - name: DB_CONNECT
              value: "mysql+mysqlconnector://root:AVdLiMJVPJoxcytCdJfiTyVbnFmxGcTT@gondola.proxy.rlwy.net:27694/railway"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_KEY
            - name: STRIPE_SECRET_KEY
              value: "sk_test_51R8jsFCAERKUWFVyMTNRxoqV3Y75UdDG6qqzqQ1IOwpXV4Og23voirSMlJBRDF20SWgMJl0WJsW1eDiqAU003PiF00aPiMEDPB"
            - name: LOGS_PATH
              value: /app/logs
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: FRONTEND_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: log
          hostPath:
            path: /app/logs
