apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: m3t4-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: VITE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_BASE_URL
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_API_URL
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
