name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "Backend/**" 
  pull_request:
    branches: [ "main" ]
    paths:
      - "Backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image - Backend
        uses: docker/build-push-action@v5
        with:
          context: Backend/
          file: Backend/Dockerfile  
          push: true  
          tags: ${{ secrets.DOCKER_USERNAME }}/m3t4-backend:latest

